name: Build and Release Workflow

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    uses: ./.github/workflows/build_test.yml

  build_release:
    uses: ./.github/workflows/build_release.yml
    needs: tag_release

  tag_release:
    uses: ./.github/workflows/tag_release.yml
    needs: build_test
    secrets: inherit

