name: build_release
  
on:
  workflow_call:
    inputs: {}

jobs:
  build-and-archive:
    name: Build and Archive Library
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up GCC
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build Static Library
      - name: Build Static Library
        run: make lib

      # Step 4: Cache the 'release' folder
      - name: Cache Release Folder
        id: cache-release
        uses: actions/cache@v4
        with:
          path: release
          key: release-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            release-${{ github.sha }}-
            release-

      # Step 5: Archive Static Library and Headers
      - name: Archive Library and Headers
        run: |
          mkdir -p release
          cp ./bin/libarray_op.a release
          cp -r ./include release

      # Step 6: Upload Release Artifacts
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: array_op_lib
          path: release
          retention-days: 1
