name: build_release
  
on:
  workflow_call:
    inputs: {}

jobs:
  build-and-archive:
    name: Build and Archive Library
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up GCC
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build Static Library
      - name: Build Static Library
        run: make lib

      # Step 4: Archive Static Library and Headers
      - name: Archive Library and Headers
        run: |
          mkdir -p release
          cp ./bin/libarray_op.a release
          cp -r ./include release

      # Step 5: Upload Release Artifacts
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: array_op_lib
          path: release
          retention-days: 1

      # Step 6: Upload Release Assets
      - name: Upload Assets to Release
        uses: ncipollo/release-action@v1
        with:
          files: './release/*'
