name: build_test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: build_test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up GCC
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Run tests
      - name: Run Tests
        run: make test
