name: Build and Release Workflow

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    uses: ./.github/workflows/build_test.yml

  build_release:
    uses: ./.github/workflows/build_release.yml
    needs: build_test

  tag_release:
    uses: ./.github/workflows/tag_release.yml
    needs: build_release
    secrets: inherit

  generate_changelog:
    uses: ./.github/workflows/generate_changelog.yml
    needs: tag_release
    secrets: inherit
  
  cleanup_cache:
    runs-on: ubuntu-latest
    needs: generate_changelog
    if: failure() || success()
    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Delete the cached folder if job failed or completed
      - name: Delete Cached Release Folder
        run: |
          if [ -d release ]; then
            echo "Deleting the cached release folder..."
            rm -rf release
          else
            echo "No release folder found to delete."
          fi
