name: Build and Release Workflow

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Import Build and Test job
  build_test:
    uses: ./.github/workflows/build_test.yml

  build_release:
    uses: ./.github/workflows/build_release.yml
    needs: build_test

  tag_release:
    uses: ./.github/workflows/tag_release.yml
    needs: build_release
    secrets: inherit

  generate_changelog:
    uses: ./.github/workflows/generate_changelog.yml
    needs: tag_release
    secrets: inherit
