name: generate_changelog
  
on:
  workflow_call:
    inputs: {}

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install conventional-changelog CLI
      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      # Step 3: Generate Changelog
      - name: Generate Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      # Step 4: Commit the updated changelog
      - name: Commit Changelog
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG"
          git push
