name: tag_release
  
on:
  workflow_call:
    inputs: {}

jobs:
  tag-and-release:
    name: tag_release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Fetch all tags
      - name: Fetch Tags
        uses: actions/checkout@v4
        run: git fetch --tags

      # Step 3: Determine Tag Base
      - name: Calculate Next Tag
        uses: actions/checkout@v4
        id: calculate_tag
        run: |
          # Fetch all tags
          git fetch --tags --force

          # Get the latest tag
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Extract major, minor, and patch parts
          MAJOR=$(echo "$LAST_TAG" | cut -d '.' -f 1 | tr -d 'v')
          MINOR=$(echo "$LAST_TAG" | cut -d '.' -f 2)
          PATCH=$(echo "$LAST_TAG" | cut -d '.' -f 3)

          # Increment the minor part
          if [[ "$LAST_TAG" == "v0.0.0" ]]; then
            MINOR=1
          else
            MINOR=$((MINOR + 1))
          fi

          # Construct the new tag
          NEW_TAG="v${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"

          # Output the new tag
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      # Step 4: Create and Push the Tag
      - name: Create and Push Tag
        uses: ncipollo/release-action@v1

        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}

      # Step 5: Download Release Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: array_op_lib
          path: release
      
      # Step 6: Create GitHub Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release"
          tag: ${{ env.NEW_TAG }}
          name: "Release ${{ env.NEW_TAG }}"
          artifacts: release
