name: tag_release

on:
  workflow_call:
    inputs: {}

jobs:
  tag_release:
    name: tag_release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Fetch all tags
      - name: Fetch Tags
        run: git fetch --tags --force

      # Step 3: Determine Tag Base
      - name: Calculate Next Tag
        run: |
          # Get the latest tag
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Extract major, minor, and patch parts
          MAJOR=$(echo "$LAST_TAG" | cut -d '.' -f 1 | tr -d 'v')
          MINOR=$(echo "$LAST_TAG" | cut -d '.' -f 2)
          PATCH=$(echo "$LAST_TAG" | cut -d '.' -f 3)

          # Increment the minor part
          if [[ "$LAST_TAG" == "v0.0.0" ]]; then
            MINOR=1
          else
            MINOR=$((MINOR + 1))
          fi

          # Construct the new tag
          NEW_TAG="v${MAJOR}.${MINOR}.${{ github.run_number }}"

          # Output the new tag
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      # Step 4: Create and Push the Tag
      - name: Create and Push Tag
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
